spring:
  application:
    name: DaejeonYeojido

  profiles:
    active: local-mysql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: debug